[package]
name = "rpc-dll"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "darpc"
crate-type = ["cdylib"]

[dependencies]
darpc-game-client.workspace = true
darpc-hook.workspace = true
darpc-model.workspace = true
darpc-protocol.workspace = true
darpc-win32.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_Com",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
] }

[lints]
workspace = true
