[package]
name = "darpc-game-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
darpc-model.workspace = true
darpc-win32.workspace = true
sha2.workspace = true

[lints]
workspace = true
