[package]
name = "loader-fixture-dll"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "darpc_fixture"
crate-type = ["cdylib"]

[dependencies]
darpc-win32.workspace = true

[lints]
workspace = true
