[package]
name = "rpc-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "darpc"
path = "src/main.rs"

[dependencies]
darpc-model.workspace = true
darpc-protocol.workspace = true
darpc-win32.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation"] }

[lints]
workspace = true
